version: "3"

services:
  web:
    build: .
    restart: always
    depends_on:
      - mongo
    ports:
      - "8000:8000"

  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - mongodb_data:/data/db
    expose:
      - "27017"

volumes:
  mongodb_data:
